local t = Def.ActorFrame{
	LoadActor("bg_color")..{
	InitCommand=cmd(x,320;y,SCREEN_CENTER_Y;diffusealpha,8);
	};
	LoadActor("bg2")..{
	InitCommand=cmd(x,320;y,SCREEN_CENTER_Y;diffusealpha,8);
	OnCommand=cmd(zoom,2;diffusealpha,.8;linear,2.5;zoom,1);
	};
	LoadActor("bg.png")..{
	InitCommand=cmd(x,320;y,SCREEN_CENTER_Y;blend,'BlendMode_Add');
	OnCommand=cmd(zoom,3;diffusealpha,.3;linear,3;zoom,2;diffusealpha,0);
	};
	LoadActor("1")..{
	InitCommand=cmd(x,320;y,SCREEN_CENTER_Y-188);
	OnCommand=cmd(diffusealpha,0;addy,200;linear,.3;addy,-200;diffusealpha,.8);
	};
	LoadActor("2.png")..{
	InitCommand=cmd(x,290;y,SCREEN_CENTER_Y-57);
	OnCommand=cmd(diffusealpha,0;addx,-200;linear,.3;addx,200;diffusealpha,.8);
	};
	LoadActor("3.png")..{
	InitCommand=cmd(x,283;y,SCREEN_CENTER_Y+33);
	OnCommand=cmd(diffusealpha,0;addy,-200;linear,.3;addy,200;diffusealpha,.8);
	};
	LoadActor("4.png")..{
	InitCommand=cmd(x,600;y,SCREEN_CENTER_Y-50);
	OnCommand=cmd(diffusealpha,0;addx,100;linear,.2;addx,-100;diffusealpha,.8;);
	};
	LoadActor("5.png")..{
	InitCommand=cmd(x,154;y,SCREEN_CENTER_Y+139);
	OnCommand=cmd(diffusealpha,0;addx,-300;sleep,.1;linear,.3;addx,300;diffusealpha,.8);
	};
	LoadActor("glow.png")..{
	InitCommand=cmd(x,320;y,SCREEN_CENTER_Y;blend,'BlendMode_Add');
	OnCommand=cmd(zoom,2;diffusealpha,.2);
	};
	LoadActor("gradient.png")..{
	InitCommand=cmd(x,320;y,SCREEN_CENTER_Y);
	OnCommand=cmd(diffusealpha,1);
	};
	LoadActor("ring.png")..{
	InitCommand=cmd(x,320;y,SCREEN_CENTER_Y);
	OnCommand=cmd(zoom,.8;diffusealpha,0;linear,.3;zoom,1;diffusealpha,1;sleep,2.8;diffusealpha,0);
	};
	LoadActor("MUSIC_WAKU_BG")..{
	InitCommand=cmd(x,320;y,SCREEN_CENTER_Y-46;blend,'BlendMode_Add');
	OnCommand=cmd(texcoordvelocity,-.1,0;diffusealpha,0.8;zoomy,0;sleep,.3;linear,.2;zoomy,1.05;linear,.1;zoomy,1);
	};
	LoadActor("_songtitle")..{
	};
	LoadActor("_coursetitle")..{
	};
	Def.Quad{
	InitCommand=cmd(diffuse,color("#FFFFFF");x,320;y,SCREEN_CENTER_Y;zoomtowidth,SCREEN_WIDTH;zoomtoheight,SCREEN_HEIGHT;blend,'BlendMode_Add');
	OnCommand=cmd(linear,.2;diffusealpha,0);
	};
	Def.Quad{
	InitCommand=cmd(diffuse,color("#000000");x,320;y,SCREEN_CENTER_Y;zoomtowidth,SCREEN_WIDTH;zoomtoheight,SCREEN_HEIGHT);
	OnCommand=cmd(diffusealpha,0;sleep,2;linear,0.4;diffusealpha,.4);
	};
	-------------------------------------
	LoadActor("bg.png")..{
	InitCommand=cmd(x,320;y,SCREEN_CENTER_Y;blend,'BlendMode_Add');
	OnCommand=cmd(diffusealpha,0;sleep,2.4;diffusealpha,.6;linear,.6;zoom,.6);
	};
	LoadActor("bg.png")..{
	InitCommand=cmd(x,320;y,SCREEN_CENTER_Y;blend,'BlendMode_Add');
	OnCommand=cmd(diffusealpha,0;sleep,2.4;diffusealpha,.6;linear,.6;zoom,1.3);
	};
	LoadActor("bg.png")..{
	InitCommand=cmd(x,320;y,SCREEN_CENTER_Y;blend,'BlendMode_Add');
	OnCommand=cmd(diffusealpha,0;sleep,2.4;diffusealpha,.6;linear,.6;zoom,2);
	};
	--------------------------------------
	-- OPTIONS ---------------------------
	LoadActor("OPTIONS")..{
	};
	--------------------------------------
	--Layer180
	LoadActor("glow.png")..{
	InitCommand=cmd(x,320;y,SCREEN_CENTER_Y;blend,'BlendMode_Add');
	OnCommand=cmd(zoom,2;zoomx,3;diffusealpha,0;sleep,2.4;diffusealpha,1;linear,.5;diffusealpha,0);
	};
	LoadActor("glow.png")..{
	InitCommand=cmd(x,320;y,SCREEN_CENTER_Y;blend,'BlendMode_Add');
	OnCommand=cmd(zoom,2;zoomx,3;diffusealpha,0;sleep,2.4;diffusealpha,1;linear,.5;diffusealpha,0);
	};
	Def.Quad{
	InitCommand=cmd(x,320;y,SCREEN_CENTER_Y;zoomtowidth,SCREEN_WIDTH;zoomtoheight,SCREEN_HEIGHT;diffuse,color("#000000"));
	OnCommand=cmd(diffusealpha,0;sleep,2.5;linear,0.3;diffusealpha,1);
	};
};

return t;