-- GenreGen, Version 1.1
-- Written by Vyhd (http://boxorroxors.net/)

-- Licensed under Creative Commons Attribution-Share Alike 3.0 Unported
-- ( http://creativecommons.org/licenses/by-sa/3.0/ )
-- All I ask is that you keep this notice intact. :)

-- Shoutouts to Konami for making an awesome game and filling it with
-- ridiculous genres. Every single string here is straight from IIDX. :>

GenreGen = {}

GenreGen.Defs =
{
	-- the main genre. may be listed on its own.
	Main =
	{
		"2STEP",
		"AFRICA",
		"AMBIENT",
		"AMERICA",
		"BAROQUE",
		"BEAT",
		"BOSSA",
		"BREAKS", 
		"BREAKBEAT",
		"CABARET",
		"CELTRANCE",
		"CHANSON",
		"CHOIR",
		"CONCERTO",
		"CROSSOVER",
		"CUDDLECORE",
		"DANCE",
		"DIRGE",
		"DISCO",
		"DRUM & BASS",
		"ELECTRO",
		"ELECTROCK",
		"ELECTRONIC",
		"EXTREME",
		"FRANCE",
		"FULL ON",
		"FUNK",
		"FUSION",
		"GABBA",
		"GABBER",
		"HANDZ UP",
		"HARDCORE",
		"HOUSE",
		"INSTRUMENTAL",
		"JAPAN", 
		"J-POP",
		"J-POP+",
		"J-ROCK",
		"JUNGLE",
		"K-GROOVE",
		"LATIN HORNS",
		"LOUNGE",
		"MINIMAL",
		"MIXTURE",
		"NU-NRG",
		"OPERA",
		"OPUS",
		"ORATORIO",
		"ORCHESTRAL",
		"PARADISE",
		"PIANO'N'BASS",
		"POETRY",
		"POP",
		"POPS",
		"PROGRESSIVE",
		"PSYCHEDELIC",
		"RENAISSANCE",
		"REQUIEM",
		"ROCK",
		"SALSA",
		"SCHRANZ",
		"SLOWCORE",
		"SOFTCORE",
		"SONATA",
		"SOUL",
		"SOUND",
		"SPIRITUAL",
		"SWING",
		"TECHNO",
		"TEC-DRUM'N'BASS",
		"TEK",
		"TRANCE",
		"WALTZ",
	};

	-- a secondary descriptor, which is likely be shown.
	Desc1 =
	{
		"ASIAN",
		"BEAT",
		"BIGBEAT",
		"BROKEN",
		"BUCHIAGE",
		"CLICK",
		"CLUB",
		"COUNTRY",
		"CUTE",
		"CYBER",
		"CYBORG",
		"DEATH",
		"DEVEPTIVE",
		"DUTCH",
		"EPIC",
		"ERHU",
		"ELECTRIC",
		"ESOTERIC",
		"ETHNO",
		"EURO",
		"FREEFORM",
		"GARAGE",
		"GOA",
		"GOTHIC",
		"HAPPY",
		"HARD",
		"HINDU",
		"HIP",
		"ITALO",
		"J-HAPPY",
		"LOVERS",
		"MEDIEVAL",
		"MILLENNIUM",
		"NATURAL",
		"NOISE",
		"NOSTALISH",
		"NUSTYLE",
		"POWER",
		"PUNK",
		"RAGGA",
		"RECKLESS",
		"ROCOCO",
		"SADISTIC",
		"SCOUSE",
		"SPANISH",
		"SPEED",
		"SUBLIME",
		"SUPERNOVA",
		"TRIBAL",
		"TURKISH",
		"WORLD",
	};

	-- tertiary descriptor. shouldn't appear often.
	Desc2 =
	{
		"ALTERNATIVE",
		"DRAMATIC",
		"HIGH SPEED",
		"HYPER",
		"LOVELY",
		"OLDSKOOL",
		"NU",
		"SUPER",
		"SYNTHETIC",
	};
};