local t = Def.ActorFrame {
	LoadActor("BG_MUSIC.png")..{
		InitCommand=cmd(x,320;y,SCREEN_CENTER_Y);
		OnCommand=cmd(diffusealpha,0;addx,-15;addy,-15;linear,0.5;addx,15;addy,15;diffusealpha,0.8);
	};
	LoadActor("MUSIC_WAKU.png")..{
		InitCommand=cmd(x,326;y,SCREEN_CENTER_Y-19);
		OnCommand=cmd(blend,'BlendMode_Add';diffusealpha,0.8);
	};
	LoadActor("MUSIC_WAKU_BG.png")..{
		InitCommand=cmd(x,320;y,SCREEN_CENTER_Y);
		OnCommand=cmd(blend,'BlendMode_Add';texcoordvelocity,-.1,0;diffusealpha,0.8;x,200;y,213;cropleft,.235;cropright,.25);
	};
	LoadActor("UP_PARTS.png")..{
		InitCommand=cmd(x,299;y,SCREEN_CENTER_Y-114);
		OnCommand=cmd(blend,'BlendMode_Add';diffusealpha,0.8;addy,400;sleep,0.1;linear,0.5;addy,-350;linear,0.15;addy,-50;linear,0.4;diffusealpha,0);
	};
	LoadActor("BG_FLASH1.png")..{
		InitCommand=cmd(x,40;y,SCREEN_CENTER_Y-40);
		OnCommand=cmd(blend,'BlendMode_Add';diffusealpha,0;sleep,0.5;diffusealpha,0.7;sleep,0.1;diffusealpha,0);
	};
	LoadActor("BG_FLASH2.png")..{
		InitCommand=cmd(x,217;y,SCREEN_CENTER_Y-73);
		OnCommand=cmd(blend,'BlendMode_Add';diffusealpha,0;sleep,0.55;diffusealpha,0.7;sleep,0.1;diffusealpha,0);
	};
	LoadActor("BG_FLASH3.png")..{
		InitCommand=cmd(x,204;y,SCREEN_CENTER_Y+24);
		OnCommand=cmd(blend,'BlendMode_Add';diffusealpha,0;sleep,0.6;diffusealpha,0.7;sleep,0.1;diffusealpha,0);
	};
	LoadActor("BG_FLASH4.png")..{
		InitCommand=cmd(x,43;y,SCREEN_CENTER_Y+150);
		OnCommand=cmd(blend,'BlendMode_Add';diffusealpha,0;sleep,0.65;diffusealpha,0.7;sleep,0.1;diffusealpha,0);
	};
	LoadActor("BG_FLASH5.png")..{
		InitCommand=cmd(x,252;y,SCREEN_CENTER_Y+82);
		OnCommand=cmd(blend,'BlendMode_Add';diffusealpha,0;sleep,0.7;diffusealpha,0.7;sleep,0.1;diffusealpha,0);
	};
	LoadActor("DIFF_CHANGE.png")..{
		InitCommand=cmd(x,640;y,SCREEN_CENTER_Y-9;horizalign,right);
		OnCommand=cmd(blend,'BlendMode_Add';addx,300;linear,.3;addx,-300;linear,.2;diffusealpha,.5);
	};
};
return t;